from market import app, Item
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\00Flask\FlaskMarket\market.py", line 7, in <module>
    db = SQLAlchemy(app)
         ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 278, in __init__
    self.init_app(app)
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 373, in init_app
    self._apply_driver_defaults(options, app)
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 607, in _apply_driver_defaults
    url = sa.engine.make_url(options["url"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\sqlalchemy\engine\url.py", line 842, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\sqlalchemy\engine\url.py", line 905, in _parse_url
    return URL.create(name, **components)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\sqlalchemy\engine\url.py", line 211, in create
    cls._assert_port(port),
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\sqlalchemy\engine\url.py", line 221, in _assert_port
    return int(port)
           ^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
