from flask import Flask
from flask import render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///market.db"
db = SQLAlchemy(app) 

class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)   # Changed 'column' to 'Column' and 'integer' to 'Integer'
    name = db.Column(db.String(length=30), nullable=False, unique=True)   # Changed 'string' to 'String'
    price = db.Column(db.Integer, nullable=False)   # Changed 'integer' to 'Integer'
    barcode = db.Column(db.String(length=12), nullable=False, unique=True)   # Changed 'string' to 'String'
    description = db.Column(db.String(length=1000), nullable=False, unique=True)   # Changed 'string' to 'String'

@app.route("/")
@app.route("/home")
def home_page():
    return render_template("home.html")

@app.route("/market")
def market_page():
    items = [
    {'id': 1, 'name': 'Phone', 'barcode': '893212299897', 'price': 500},
    {'id': 2, 'name': 'Laptop', 'barcode': '123985473165', 'price': 900},
    {'id': 3, 'name': 'Keyboard', 'barcode': '231985128446', 'price': 150}
]
    return render_template("market.html", items=items)






POWERSHELL COMMANDS:-


PS C:\Python312\00Flask\FlaskMarket> python
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from market import app, db
>>> with app.app_context():            ############# i have added this lines because The error you're encountering is due to trying to access the database outside of an application context. In Flask, certain operations like database manipulation require the application context to be active. You can resolve this by using app.app_context() to set up the context before calling db.create_all().
...     db.create_all()
...
>>>

############################ when i execute these commands it should create new db file in VS Code named "market.db". But for me there is no file created. and also doesn't show any error in the powershell as well.












#####################
PS C:\Python312\00Flask\FlaskMarket> python
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from market import db
>>> db.create_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 900, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 871, in _call_for_binds
    engine = self.engines[key]
             ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\flask_sqlalchemy\extension.py", line 687, in engines
    app = current_app._get_current_object()  # type: ignore[attr-defined]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\werkzeug\local.py", line 519, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
